user.role.*.third_party.farm_access:
  type: mapping
  label: 'Farm Access'
  mapping:
    access:
      type: mapping
      label: 'Access config'
      mapping:
        config:
          type: boolean
          label: 'Grant config permissions'
        entity:
          type: mapping
          label: 'Entity permissions'
          mapping:
            view all:
              type: boolean
              label: 'Grant view permissions for all entities.'
            create all:
              type: boolean
              label: 'Grant create permissions for all entities.'
            update all:
              type: boolean
              label: 'Grant update permissions for all entities.'
            delete all:
              type: boolean
              label: 'Grant delete permissions for all entities.'
