user.role.*.third_party.farm_access:
  type: mapping
  label: 'Farm Access'
  mapping:
    access:
      type: mapping
      label: 'Access config'
      mapping:
        config:
          type: boolean
          label: 'Grant config permissions'
        entity:
          type: mapping
          label: 'Entity permissions'
          mapping:
            view all:
              type: boolean
              label: 'Grant view permissions for all entities.'
            create all:
              type: boolean
              label: 'Grant create permissions for all entities.'
            update all:
              type: boolean
              label: 'Grant update permissions for all entities.'
            delete all:
              type: boolean
              label: 'Grant delete permissions for all entities.'
            type:
              type: sequence
              label: 'Entity types'
              sequence:
                type: sequence
                label: 'Entity type'
                sequence:
                  type: sequence
                  label: 'Operation'
                  sequence:
                    type: string
                    label: 'Bundle'

# Schema for managed_role_permissions config entity.
farm_access.managed_role_permissions.*:
  type: config_entity
  label: 'Managed role permissions entity'
  mapping:
    id:
      type: string
      label: 'ID'
    default_permissions:
      type: sequence
      label: 'Default permissions'
      sequence:
        type: string
        label: 'Permission'
    config_permissions:
      type: sequence
      label: 'Config permissions'
      sequence:
        type: string
        label: 'Permission'
