<?php

/**
 * @file
 * Farm Inventory module.
 */

use Drupal\Core\Entity\EntityTypeInterface;
use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_entity_base_field_info().
 */
function farm_inventory_entity_base_field_info(EntityTypeInterface $entity_type) {
  module_load_include('inc', 'farm_inventory', 'farm_inventory.base_fields');
  switch ($entity_type->id()) {

    // Build asset base fields.
    case 'asset':
      return farm_inventory_asset_base_fields();

    // Build quantity base fields.
    case 'quantity':
      return farm_inventory_quantity_base_fields();

    default:
      return [];
  }
}

/**
 * Implements hook_form_BASE_FORM_ID_alter().
 */
function farm_inventory_form_quantity_form_alter(&$form, FormStateInterface $form_state, $form_id) {

  // Check if the form has the required inventory fields.
  if (isset($form['group']) && isset($form['inventory_adjustment'])) {

    // Set the visible state of the quantity.inventory_asset field.
    // Only display if inventory_adjustment is not NULL.
    $form['inventory_adjustment']['#states']['visible'] = [':input[name="inventory_adjustment[value]"]' => ['checked' => TRUE]];
  }
}
