name: farmOS Inventory
description: Adds inventory features to quantities.
type: module
package: farmOS
core_version_requirement: ^9
dependencies:
  - drupal:field
  - farm:asset
  - farm:farm_quantity
  - log:log
