<?php

/**
 * Farm Client module.
 */

/**
 * Implements hook_farm_info()
 */
function farm_client_farm_info() {

  // Ask modules for client module info.
  $client_modules = module_invoke_all('farm_client_module_info');

  // Add the client module info to /farm.json.
  $info = array();
  if (!empty($client_modules)) {
    $info['client'] = array(
      'modules' => $client_modules,
    );
  }

  return $info;
}
