# Schema for the configuration files of the farm_map module.
farm_map.map_type.*:
  type: config_entity
  label: 'Map'
  mapping:
    id:
      type: string
      label: 'Machine-readable name'
    label:
      type: label
      label: 'Type'
    description:
      type: text
      label: 'Description'
    behaviors:
      type: sequence
      label: 'Map behaviors'
      nullable: true
      sequence:
        type: string
        label: 'Map behavior id'
    options:
      type: sequence
      label: 'farmOS-map options'
      sequence:
        type: ignore
        label: 'Option name'
farm_map.map_behavior.*:
  type: config_entity
  label: 'Map behavior'
  mapping:
    id:
      type: string
      label: 'Machine-readable name'
    label:
      type: label
      label: 'Behavior'
    description:
      type: text
      label: 'Description'
    library:
      type: string
      label: 'Library name'
    settings:
      type: sequence
      label: 'Behavior settings'
      sequence:
        type: ignore
        label: 'Behavior setting'
block.settings.map_block:
  type: block_settings
  label: 'map block settings'
  mapping:
    map_type:
      type: string
      label: 'Map type'
