<?php

/**
 * @file
 * Contains farm_farm.module.
 */

use Drupal\Core\Entity\EntityTypeInterface;

/**
 * Implements hook_entity_base_field_info().
 */
function farm_farm_entity_base_field_info(EntityTypeInterface $entity_type) {
  $fields = [];

  // Add a Farm reference field to assets.
  if ($entity_type->id() == 'asset') {
    $options = [
      'type' => 'entity_reference',
      'label' => t('Farm'),
      'description' => t('What farm is this associated with?'),
      'target_type' => 'organization',
      'target_bundle' => 'farm',
      'multiple' => TRUE,
      'weight' => [
        'form' => 55,
        'view' => -5,
      ],
    ];
    $fields['farm'] = \Drupal::service('farm_field.factory')->baseFieldDefinition($options);
  }

  return $fields;
}

/**
 * Implements hook_farm_ui_theme_field_group_items().
 */
function farm_farm_farm_ui_theme_field_group_items(string $entity_type, string $bundle) {
  if ($entity_type == 'asset') {
    return [
      'farm' => 'meta',
    ];
  }
  return [];
}

/**
 * Implements hook_farm_ui_theme_region_items().
 */
function farm_farm_farm_ui_theme_region_items(string $entity_type) {
  if ($entity_type == 'asset') {
    return [
      'second' => [
        'farm',
      ],
    ];
  }
  return [];
}
